apiVersion: apps/v1
kind: Deployment
metadata:
  name: langua_user_microservice
  labels:
    app: langua_user_microservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: langua_user_microservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: langua_user_microservice
        tier: service
    spec:
      containers:
      - name: langua_user_microservice
        image: "prateeksingh1590/microsvc:1.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: POSTGRES_HOST
          value: "localhost"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "langua_user_micro"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: langua_user_microservice
  labels:
    app: langua_user_microservice
    tier: service
spec:
  type: NodePort
  ports:
  - port: 50051
  selector:
    app: langua_user_microservice
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: langua_user_microservice
  labels:
    app: langua_user_microservice
    tier: backend
spec:
  backend:
    serviceName: langua_user_microservice
    servicePort: 50051