apiVersion: apps/v1
kind: Deployment
metadata:
 name: langua-user-micro-db-deployment
 labels:
  app: postgres
spec:
 replicas: 1
 selector:
  matchLabels:
   app: postgres
 template:
  metadata:
   labels:
    app: postgres
  spec:
   containers:
   - name: langua-user-micro-db
     image: postgres:latest
     ports:
     - containerPort: 5432
     envFrom:
     - configMapRef:
        name: langua-user-micro-db.config
---
apiVersion: v1
kind: Service
metadata:
 name: langua-user-micro-db-service
spec:
 selector: 
  app: postgres
 clusterIP: 10.96.0.2
 ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
