apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexic-microservice-deployment
  labels:
    app: lexic-microservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: lexic_microservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: lexic_microservice
        tier: service
    spec:
      containers:
      - name: lexic-microservice
        image: "endlesslydivided/langua_lexic_microservice:latest"
        imagePullPolicy: Always
        envFrom:
         - configMapRef:
            name: lexic-microservice.config
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: lexic-microservice-service
  labels:
    app: lexic-microservice
    tier: service
spec:
  type: NodePort
  ports:
  - port: 50052
    targetPort: 50052
  clusterIP: 10.96.0.4
  selector:
    app: lexic-microservice
